from django.urls import path

from .api.views import (
    AccountDetailView,
    AccountListCreateView,
    BudgetDetailView,
    BudgetListCreateView,
    CardPurchaseDetailView,
    CardPurchaseListCreateView,
    CategoryDetailView,
    CategoryListCreateView,
    CreditCardInvoiceDetailView,
    CreditCardInvoiceListView,
    credit_card_invoice_close,
    credit_card_invoice_pay,
    CreditCardDetailView,
    CreditCardListCreateView,
    generate_recurrences_view,
    GoalDetailView,
    GoalListCreateView,
    InvestmentDetailView,
    InvestmentListCreateView,
    RecurrenceDetailView,
    RecurrenceListCreateView,
    TransactionDetailView,
    TransactionListCreateView,
    finance_overview,
    cashflow_projection_view,
)

urlpatterns = [
    path("", finance_overview, name="finance_overview"),
    path("accounts/", AccountListCreateView.as_view(), name="account_list_create"),
    path("contas/", AccountListCreateView.as_view(), name="conta_listar_criar"),
    path("accounts/<int:pk>/", AccountDetailView.as_view(), name="account_detail"),
    path("contas/<int:pk>/", AccountDetailView.as_view(), name="conta_detalhe"),
    path("categories/", CategoryListCreateView.as_view(), name="category_list_create"),
    path("categorias/", CategoryListCreateView.as_view(), name="categoria_listar_criar"),
    path("categories/<int:pk>/", CategoryDetailView.as_view(), name="category_detail"),
    path("categorias/<int:pk>/", CategoryDetailView.as_view(), name="categoria_detalhe"),
    path(
        "transactions/",
        TransactionListCreateView.as_view(),
        name="transaction_list_create",
    ),
    path(
        "transacoes/",
        TransactionListCreateView.as_view(),
        name="transacao_listar_criar",
    ),
    path(
        "transactions/<int:pk>/",
        TransactionDetailView.as_view(),
        name="transaction_detail",
    ),
    path(
        "transacoes/<int:pk>/",
        TransactionDetailView.as_view(),
        name="transacao_detalhe",
    ),
    path("credit-cards/", CreditCardListCreateView.as_view(), name="credit_card_list_create"),
    path("cartoes/", CreditCardListCreateView.as_view(), name="cartao_listar_criar"),
    path("credit-cards/<int:pk>/", CreditCardDetailView.as_view(), name="credit_card_detail"),
    path("cartoes/<int:pk>/", CreditCardDetailView.as_view(), name="cartao_detalhe"),
    path("card-purchases/", CardPurchaseListCreateView.as_view(), name="card_purchase_list_create"),
    path("parcelamentos/", CardPurchaseListCreateView.as_view(), name="parcelamento_listar_criar"),
    path("card-purchases/<int:pk>/", CardPurchaseDetailView.as_view(), name="card_purchase_detail"),
    path("parcelamentos/<int:pk>/", CardPurchaseDetailView.as_view(), name="parcelamento_detalhe"),
    path("credit-card-invoices/", CreditCardInvoiceListView.as_view(), name="credit_card_invoice_list"),
    path("faturas-cartao/", CreditCardInvoiceListView.as_view(), name="fatura_cartao_listar"),
    path("credit-card-invoices/<int:pk>/", CreditCardInvoiceDetailView.as_view(), name="credit_card_invoice_detail"),
    path("faturas-cartao/<int:pk>/", CreditCardInvoiceDetailView.as_view(), name="fatura_cartao_detalhe"),
    path("credit-card-invoices/<int:pk>/close/", credit_card_invoice_close, name="credit_card_invoice_close"),
    path("faturas-cartao/<int:pk>/fechar/", credit_card_invoice_close, name="fatura_cartao_fechar"),
    path("credit-card-invoices/<int:pk>/pay/", credit_card_invoice_pay, name="credit_card_invoice_pay"),
    path("faturas-cartao/<int:pk>/pagar/", credit_card_invoice_pay, name="fatura_cartao_pagar"),
    path("investments/", InvestmentListCreateView.as_view(), name="investment_list_create"),
    path("investimentos/", InvestmentListCreateView.as_view(), name="investimento_listar_criar"),
    path("investments/<int:pk>/", InvestmentDetailView.as_view(), name="investment_detail"),
    path("investimentos/<int:pk>/", InvestmentDetailView.as_view(), name="investimento_detalhe"),
    path("goals/", GoalListCreateView.as_view(), name="goal_list_create"),
    path("metas/", GoalListCreateView.as_view(), name="meta_listar_criar"),
    path("goals/<int:pk>/", GoalDetailView.as_view(), name="goal_detail"),
    path("metas/<int:pk>/", GoalDetailView.as_view(), name="meta_detalhe"),
    path("budgets/", BudgetListCreateView.as_view(), name="budget_list_create"),
    path("orcamentos/", BudgetListCreateView.as_view(), name="orcamento_listar_criar"),
    path("budgets/<int:pk>/", BudgetDetailView.as_view(), name="budget_detail"),
    path("orcamentos/<int:pk>/", BudgetDetailView.as_view(), name="orcamento_detalhe"),
    path("recurrences/", RecurrenceListCreateView.as_view(), name="recurrence_list_create"),
    path("recorrencias/", RecurrenceListCreateView.as_view(), name="recorrencia_listar_criar"),
    path("recurrences/<int:pk>/", RecurrenceDetailView.as_view(), name="recurrence_detail"),
    path("recorrencias/<int:pk>/", RecurrenceDetailView.as_view(), name="recorrencia_detalhe"),
    path("recurrences/generate/", generate_recurrences_view, name="recurrence_generate"),
    path("recorrencias/gerar/", generate_recurrences_view, name="recorrencia_gerar"),
    path("cashflow/", cashflow_projection_view, name="cashflow_projection"),
    path("fluxo-caixa/", cashflow_projection_view, name="fluxo_caixa"),
]
